assets/controller_deployment.yaml, assets/controller_sa.yaml, assets/node_daemonset.yaml, assets/node_sa.yaml, assets/rbac/attacher_binding.yaml, assets/rbac/controller_privileged_binding.yaml, assets/rbac/node_privileged_binding.yaml, assets/rbac/provisioner_binding.yaml, assets/rbac/resizer_binding.yaml, assets/rbac/snapshotter_binding.yaml, assets/storageclass.yaml, pkg/generated/bindata.go, pkg/operator/operator_test.go
=> Use better resource names and defaults

pkg/operator/operator_test.go
=> Fix unit tests after API bump

README.md, assets/controller_deployment.yaml, assets/node_daemonset.yaml, pkg/generated/bindata.go, pkg/operator/operator_test.go, pkg/operator/sync.go
=> Fix log level

README.md
=> TODO list has been migrated to GH issues

manifests/4.5/aws-ebs-csi-driver-operator.v4.5.0.clusterserviceversion.yaml
It is a subset of privileged SCC.
Fixes: #18
=> Remove hostmount-anyuid SCC from the operator

assets/controller_deployment.yaml, assets/node_daemonset.yaml, bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml, hack/start.sh, pkg/generated/bindata.go, pkg/operator/operator_test.go
Fixes https://github.com/openshift/aws-ebs-csi-driver-operator/issues/37
=> Use quay.io for the operator and driver images

README.md
Also remove quick start section because we don't want
people to use index-image from a personal quay.io account
=> Document how to install OPM tool

bundle/manifests/aws-csi-driver.crd.yaml, bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
* The operator can handle "Full Lifecycle".
* Add validation to LogLevels - console then offers a nice drop-box GUI.
* Add log  levels to the example.
=> Bug 1828963: Fix the operator CSV and CRD

bundle/manifests/aws-csi-driver.crd.yaml
Rework the CRD to v1 API, which allows defaulting and add default values for log levels and ManagementState.
=> Bug 1835604: Add defaulting to driver.Spec fields

bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
=> Bug 1842402: Add word "Driver" to displayName

pkg/operator/operator.go
According to  [1] `Progressing` indicates that the operator is trying to transition the operand to a different state.
I believe this should be the right state for the operator when it's waiting for PVs to be deleted.
[1] https://github.com/bertinatto/aws-ebs-csi-driver-operator-1/blob/5b6707e991b0f728501f8ce61db6a87e0f06fa31/vendor/github.com/openshift/api/operator/v1/types.go#L137
=> Bug 1843579: Set progressing condition when removing operand

assets/rbac/resizer_role.yaml, pkg/generated/bindata.go
https://github.com/kubernetes-csi/external-resizer/issues/88
=> Newer resizer needs ability to list/watch all pods

manifests/05_clusterrole.yaml
Backport https://github.com/openshift/cluster-storage-operator/pull/73
=> Add pod-listing permissions

assets/controller.yaml, pkg/generated/bindata.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1872500
cc @openshift/sig-storage
=> Bug 1872500: csiTimeout has been removed in favour of timeout parameter

assets/controller.yaml, pkg/generated/bindata.go
=> Bug 1873168: set resizer context timeout to 120s

assets/node.yaml, pkg/generated/bindata.go
See https://bugzilla.redhat.com/show_bug.cgi?id=1881298
=> Bug 1881298: Run the node DaemonSet only on Linux nodes

test/e2e/manifest.yaml
The driver supports topology, so let's test it.
=> Bug 1898851: Enable topology tests for the driver

pkg/operator/starter.go, pkg/operator/starter_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2074706
=> Bug 2074706: Set custom endpoint environment variable if available

pkg/operator/starter.go, pkg/operator/starter_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2077894
=> Bug 2077894: Set custom endpoint environment variable if available

assets/controller.yaml, go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/config/serving/server.go, vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, vendor/modules.txt
https://issues.redhat.com/browse/OCPBUGS-4347
/cc @openshift/storage
=> OCPBUGS-4347: set TLS cipher suites in Kube RBAC sidecars

README.md
updating url based on docs from: https://github.com/openshift/aws-ebs-csi-driver/blob/master/docs/install.md#installation-1
=> [#177] fix 404 in readme

.github/dependabot.yaml
We want to get tests started automatically.
=> Add ok-to-test label to dependabot PRs

assets/controller.yaml, assets/node.yaml
=> OCPBUGS-8752: fix: typo

assets/controller.yaml, assets/node.yaml
=> [release-4.13] OCPBUGS-10405: feat: add workload annotation to deployment and daemonset

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go, vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go, vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go, vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, vendor/modules.txt
Set affinity, tolerations, node selector and priority rules for operands in the hosted control plane.
=> OCPBUGS-8691: Hypershift: set control plane operand properties

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go, vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go, vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, vendor/modules.txt
This is a manual cherry-pick of https://github.com/openshift/aws-ebs-csi-driver-operator/pull/205 to 4.13
=> [4.13] OCPBUGS-10645: Hypershift: set control plane operand properties

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/config/serving/server.go, vendor/github.com/openshift/library-go/pkg/crypto/crypto.go, vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go, vendor/modules.txt
This is a manual cherry-pick of https://github.com/openshift/aws-ebs-csi-driver-operator/pull/206 to 4.12
=> 4.12: OCPBUGS-10646: 4.12 hypershift set control plane

pkg/operator/starter.go, pkg/operator/starter_test.go
continuing work of
* https://github.com/openshift/cluster-storage-operator/pull/392
* https://github.com/openshift/hypershift/pull/2882
* https://github.com/openshift/cluster-storage-operator/pull/393
=> STOR-1432: hypershift: deploy controller with control plane release images

assets/controller.yaml
https://issues.redhat.com/browse/OCPBUGS-18417
cc @openshift/storage
=> [4.12] OCPBUGS-18417: set TLS cipher suites in Kube RBAC sidecars
