vendor/github.com/getsentry/raven-go/Dockerfile.test
Dockerfile.test is hidden by .gitignore, however it's necessary to be in the repository so make verify-deps passes.
=> Add missing deps

Makefile
Default to `registry.svc.ci.openshift.org/ocp/4.5:aws-ebs-csi-driver-operator`
=> Bump OCP version in image name

.gitignore, Makefile, manifests/03_cr.yaml
So a prow job can just run `make test-e2e` and we can change the implementation without changing the prow job.
Fix log levels in CR to make sure `make test-e2e` passes.
=> Add test-e2e Makefile target

Makefile, hack/e2e.sh, hack/start.sh
Second attempt to add e2e tests to this repo.
There is no `/bin/make` in our e2e, create a bash script.
=> Rework e2e tests from Makefile to a script

README.md, go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/modules.txt
CC @openshift/storage 
This fixes an issue where the StorageClass was always updated when the operator syncs.
=> Bump openshift/library-go

hack/start.sh
Our e2e tests don't have kubectl.
=> Use /bin/oc when available in e2e tests

Dockerfile.test
The new image is going to be used in e2e tests of other images (sidecars, AWS EBS CSI driver, origin) to get to scripts & manifests of the operator.
Copying all files for now - refactoring both in corresponding prow jobs and in this repo (at lease `hack/` and `manifest/`)  is expected and I want to avoid changing the image every time I need another file in the prow job.
=> Add image with e2e test scripts & manifests

manifests/4.5/aws-csi-driver.crd.yaml
Only `name: cluster` is allowed. Using `enum`, because it has better error message than `pattern:`
With `enum`:
```
The Driver "clusterX" is invalid: metadata.name: Unsupported value: "clusterX": supported values: "cluster"
```
With `pattern: "^cluster$"`:
```
The Driver "clusterX" is invalid: metadata.name: Invalid value: "": metadata.name in body should match '^cluster$'
```
Fixes: #21
=> Validate CR name

Dockerfile.test, hack/start.sh
Another e2e preparation PR... Now the set up is easier: ship whole repository in Dockerfile.test. Using "src", because it contains the repo + `jq` + python yaml module.
This image will be run in e2e jobs, with `oc` and `openshift-tests` injected there, see https://github.com/openshift/release/pull/8067 for details.
\+ fix one potentially uninitalized variable in e2e scripts
=> Finish e2e test preparation

assets/controller_deployment.yaml, pkg/generated/bindata.go
The controller pods should not start until a secret with AWS credentials is present.
With this patch, controller pods are in `CreateContainerConfigError` state with this event until the secret is present:
Error: secret "aws-cloud-credentials" not found
=> Make credentials secret required

hack/e2e.sh
Topology tests need all nodes to have the driver and propagate their topology to Node objects.
This could de-flake topology tests, e.g. in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_csi-external-provisioner/28/pull-ci-openshift-csi-external-provisioner-master-e2e-aws-csi/3
cc @gnufied @bertinatto
=> Wait for pods before starting e2e tests

pkg/operator/credential_request.go, pkg/operator/operator.go, pkg/operator/operator_test.go, pkg/operator/sync.go
The operator may need to update the operands (Deployment, DaemonSet) when:
* The images are changed by env. variables.
* Log level changes in CR.
* New operator starts and has updated bindata.
It's nearly impossible to detect these changes, therefore hash whole Deployment / DaemonSet .Spec and make sure the new objects are applied when the hash gets different.
cc @bertinatto @gnufied
=> Update the operand when image changes

pkg/operator/operator.go
Currently, if the operator tries to delete the CSI driver if the CR doesn't exist. This behaviour was introduced before we started using a finalizer (1fd546053c751a17f86d8c5fd92ef7b81715ea1b).
With this patch, the operator will delete the driver **only** if the CR has a deletion timestamp. It keeps logging a warning when the CR isn't found.
=> Bug 1826285: Don't delete driver if CR doesn't exist

bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
By using AllNamespaces installMode only. OLM won't allow the operator to be installed for second time with this mode.
=> Bug 1835716: Allow the operator to be installed only once

pkg/operator/credential_request.go, pkg/operator/credential_request_test.go
`CredentialsRequest` conditions can carry interesting information, such as "Cannot exceed quota for UsersPerAccount". Therefore pass this information into the driver CR conditions.
Parsing `Unstructured`, because importing controller-runtime based `v1/CredentialsRequest` from
`github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1` was not possible at time of writing this commit (go mod conflicts).
=> Bug 1835726: Report error conditions on CredentialsRequest on the driver CR

bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml, pkg/operator/operator.go
`RELATED_IMAGE_*` is required by our internal build system.
=> Bug 1836834: Rename env. variables

assets/csidriver.yaml, pkg/generated/bindata.go, pkg/operator/operator.go, pkg/operator/operator_test.go, pkg/operator/starter.go, pkg/operator/sync.go
The operator should refuse to manage CSI driver that has been installed manully by cluster admin (or another operator).
"CSI driver that has been installed manually" is detected this way:
- CSIDriver exists and does not have OCP annotation.
- OR CSIDriver does not exist
- AND namespace `opesnhift-aws-ebs-csi-driver` does not exist
- AND there is at least one CSINode that has the driver
To properly report Progressing and PrereqSatisfied conditions, condition handling has been changed considerably.
=> Bug 1835778: Detect CSI driver installed by cluster admin

pkg/operator/operator.go
The previous PR #54 did not include sending the message from cloud credentials operator, add it here.
=> Bug 1835726: Actually use error message from the credentials operator

bundle/manifests/aws-csi-driver.crd.yaml
This reverts commit 708230e049bc9ece879f52ee865dfbc6c967eb07.
Restore v1beta1 CRD, our operator pipeline does not support v1 yet. I reopened https://bugzilla.redhat.com/show_bug.cgi?id=1835604 to fix it later, when we have bundle images.
=> Bug 1839720: Revert "Add defaulting to driver.Spec fields"

assets/controller.yaml, assets/node.yaml, manifests/07_deployment.yaml, pkg/generated/bindata.go
Adding memory/cpu requirements, which should move the QoS from BestEffort to Burstable.
See https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-storage-operator/59/pull-ci-openshift-cluster-storage-operator-master-e2e-aws/1288039129833017344
=> Fix the operator images and assets

assets/controller.yaml, pkg/generated/bindata.go
This is to avoid multiple invocations of modify volume call
against same volume.
This is currently just a theory of mine that because of context timeouts, we are actually issuing multiple modifyvolume calls. This can't happen with in-tree driver because the whole operation is blocking with no timeout whatsoever. 
cc @openshift/sig-storage
=> Increase CSI resizer context timeout

manifests/07_deployment.yaml
OCP must use IfNotPresent. There is a test in e2e that catches this.
=> Don't use Always pull policy

assets/node.yaml, pkg/generated/bindata.go
Any node should be able to use PVCs. We don't know in advance what taints will be used in the cluster.
=> Bug 1863055: CSI drivers should tolerate any taints

test/e2e/manifest.yaml, test/e2e/storageclass.yaml
The storage class should be created during cluster setup. It simplifies subsequent e2e tests, as they don't need to find storage class YAML and make sure it's in the right directory (i.e. in the current directory where the tests run).
=> Use installed StorageClass for tests

assets/rbac/attacher_role.yaml, manifests/05_clusterrole.yaml, pkg/generated/bindata.go
v3.0.0 of the external-attacher uses PATCH to update `volumeattachment/status`
=> Bug 1871051: Add external-attacher permissions to patch status

assets/controller.yaml, manifests/07_deployment.yaml, pkg/generated/bindata.go
Controllers should run on master nodes. Operators should run on master nodes as well, so update the operator manifest too (although it's here just for reference, as the the CSO uses the manifest from its own repo.
=> Bug 1871998: Schedule CSI Controller on master nodes

assets/controller.yaml, pkg/generated/bindata.go
We wait for approx 287 seconds while resizing the volume,
having a shorter context timeout is problematic because context will
expire before driver is finished waiting for volume to be resized
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1877084
cc @openshift/sig-storage
=> Bug 1877084: Increase resizer timeout to 300s

assets/controller.yaml, pkg/generated/bindata.go
* `--provisioner` has been deprecated and removed upstream.
=> Bug 1876791: Update provisioner container to v2.0.0

assets/controller.yaml, pkg/generated/bindata.go
This is needed after rebase to external-provisioner v2.0.0, which does not set any default fsType.
=> Bug 1876791: Add default fsType to provisioned PVs

assets/controller.yaml, assets/node.yaml, pkg/generated/bindata.go
[9xxx range is allowed to be accessible from outside of nodes](https://github.com/openshift/openshift-docs/blob/master/modules/installation-network-user-infra.adoc) and we don't need that for CSI driver liveness probes.
Using 10300 does not make it blocked by firewall, but at least it's not in the list of open ports and it's blocked in IPI.
Also add the liveness probe sidecar to controller pod(s), they have the port open, but nobody was listening there.
=> Bug 1879406: Use port 10300-10301 for liveness probes

Dockerfile.rhel7
Updating ose-aws-ebs-csi-driver-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-aws-ebs-csi-driver-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating ose-aws-ebs-csi-driver-operator builder & base images to be consistent with ART

test/e2e/manifest.yaml
AWS EBS supports running multiple pods with as single volume on a single node, let's test it.
=> Bug 1898851: Add multipods tests

assets/controller.yaml, pkg/generated/bindata.go
xref: https://issues.redhat.com/browse/CO-1298
The controller currently accepts the access key & secret key directly from the secret. This makes sure the pod starts after the secret is populated.
With this change, we mount the same secret to the pod to ensure that the pod starts after secret is created. But the env vars sources are updated to optional
since these keys might no longer be present in secret that is using aws config to configure the AWS SDK.
`AWS_SDK_LOAD_CONFIG` and `AWS_CONFIG_FILE` env variables are added to make sure the SDK tried to load the crendetials from the file specified. In cases
where the secret does not have the credentials key, this file will not exist and SDK will skip non-readable files see https://github.com/aws/aws-sdk-go/blob/87f0aa4be0153f21470e7a9802ebfb3 …
=> assets/controller.yaml: support using aws config for credentials

assets/controller.yaml, assets/node.yaml, pkg/generated/bindata.go, pkg/operator/starter.go, pkg/operator/starter_test.go
This PR uses changes from openshift/library-go#976 to apply the proxy config to the CSI Controller Deployment fixes.
=> Bug 1912945: Set proxy config in Deployment containers

assets/controller.yaml, pkg/generated/bindata.go, pkg/operator/starter.go, pkg/operator/starter_test.go
The determination about whether a custom CA bundle is being used is assessed when the operator starts. This can lead to incorrect behavior if the kube-cloud-config ConfigMap has not yet been created in the openshit-config-managed namespace when the operator starts. Instead of only looking for the ConfigMap at start-up, these changes will have the operator looking for the ConfigMap on every reconcile and adjusting the controller deployment accordingly.
=> Bug 1905119: dynamically update controller asset for custom CA bundle

assets/controller.yaml, go.mod, go.sum, pkg/generated/bindata.go, vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go, vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go, vendor/modules.txt
Use the one provided by CSO in the operator env. variables.
=> Fix kube-rbac-proxy image reference

assets/controller.yaml, assets/service.yaml, assets/servicemonitor.yaml, manifests/11_deployment.yaml, pkg/generated/bindata.go
This PR exposes metrics from `csi-driver` container
Currently all the sidecar containers exposes scrape targets, except the `csi-driver` container
=> Bug 1951952: Metrics for cloudprovider error requests are lost

.ci-operator.yaml, Dockerfile.rhel7, pkg/dependencymagnet/dependencymagnet.go
Reconciling with https://github.com/openshift/ocp-build-data/tree/5b89f5b601508a0bcc0399fd3f34b7aa2e86e90e/images/ose-aws-ebs-csi-driver-operator.yml
Replaces https://github.com/openshift/aws-ebs-csi-driver-operator/pull/142
/cc @openshift/storage
=> Updating ose-aws-ebs-csi-driver-operator images to be consistent with ART

assets/controller.yaml, assets/node.yaml
When log level is changed in clustercsidriver it needs to propagate to a liveness probe container as well through a value passed to --v argument.
=> Bug 2028484: AWS EBS CSI driver's livenessprobe does not respect operator's loglevel

assets/csidriver.yaml, go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/modules.txt
And other CSIDriver fields. Since volumes of this CSI driver always support `fsGroup`, don't depend on Kubernetes heuristics (`ReadWriteOnceWithFSType`) and always apply it.
This updates library-go to https://github.com/openshift/library-go/pull/1324 to re-create driver's CSIDriver instance if the operator needs to change it.
It's somewhat related to https://bugzilla.redhat.com/show_bug.cgi?id=2058626, it makes sure the BZ never happens again.
=> Set CSIDriver fsGroupPolicy

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go, vendor/modules.txt
This is a library-go bump to get https://github.com/openshift/library-go/pull/1328.
Copying here a naive benchmark from that PR:
Before this patch, on a fresh-installed cluster, without user workloads, we can see that the amount of requests keep growing:
```
$ oc dev_tool audit -f must-gather.local.6142475801866269614/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-de53ed4750def9ed611ca460c780cc78eece525162747213cfdbb4c26687460c/audit_logs/kube-apiserver/ -otop --by=verb --user="system:serviceaccount:openshift-cluster-csi-drivers:aws-ebs-csi-driver-operator"  --resource="configmaps" --failed-only
had 5547 line read failures
count: 206, first: 2022-03-12T08:44:24-03:00, last: 2022-03-12T09:04:49-03:00, duration: 20m24.691542s
Top 10 "DELETE" (of 103 total hits):
103x [ 11.668456ms] …
```
=> Bug 2049671: avoid excessive GET and DELETE in ResourcesSync controller 

pkg/operator/starter.go
go 1.19 changed formatting, reformat the code.
See https://github.com/openshift/aws-ebs-csi-driver-operator/pull/162 for the formatting failures.
=> Reformat for go 1.19

pkg/operator/starter.go
https://github.com/openshift/aws-ebs-csi-driver-operator/pull/159 was created before https://github.com/openshift/aws-ebs-csi-driver-operator/pull/164, but the latter merged first. As a result, we had to rebase and refactor the former to accommodate the new functionality, introducing this regression.
=> OCPBUGS-3978: Don't deploy VolumeSnapshotClass in static controller

pkg/operator/starter.go
https://github.com/openshift/aws-ebs-csi-driver-operator/pull/159 was created before https://github.com/openshift/aws-ebs-csi-driver-operator/pull/164, but the latter merged first. As a result, we had to rebase and refactor the former to accommodate the new functionality, introducing this regression.
=> [release-4.12] OCPBUGS-1904: Don't deploy VolumeSnapshotClass in static controller

pkg/operator/starter.go
HyperShift needs guest cluster control plane components with priority `"hypershift-control-plane"`, https://hypershift-docs.netlify.app/how-to/distribute-hosted-cluster-workloads/
=> OCPBUGS-3990: Add HyperShift specific priorityClass

pkg/operator/starter.go
https://issues.redhat.com/browse/OCPBUGS-4491
=> OCPBUGS-4491: hypershift: use correct kubeconfig secret

.github/dependabot.yaml
We want to try out dependabot on this repo and see how it goes.
/cc @openshift/storage
No customer visible changes from this.
/label docs-approved
/label qe-approved
/label px-approved
=> add dependabot config for gomod updates

pkg/operator/starter.go
hypershift proxy conformance is failing because dynamic PVs are failing to provision because the `aws-ebs-csi-driver-operator` is configured with proxy when it shouldn't be
https://k8s-testgrid.appspot.com/redhat-hypershift#4.13-conformance-aws-ovn-proxy&width=20
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-aws-ovn-proxy/1627865954157334528/artifacts/conformance-aws-ovn-proxy/dump/artifacts/namespaces/clusters-5dc04e74aa4e7c327a93/apps/deployments/aws-ebs-csi-driver-controller.yaml
=> OCPBUGS-7837: do not inject-proxy when deploying in hypershift control plane

assets/controller.yaml, assets/node.yaml
Add annotation to controller deployment and node daemonset for workload pinning, this allows workload admission webhook to correctly modify the resources to allow the workload pinning feature to operate as desired.
Related to the enhancements below:
https://github.com/openshift/enhancements/pull/703
https://github.com/openshift/enhancements/pull/1213
=> OCPBUGS-8752: feat: add workload annotation to deployment and daemonset

assets/assets.go, assets/hypershift/controller_sa.yaml, pkg/operator/starter.go
Allowing the controller pod to access private images, such as those built by cluster-bot.  The controller analog to
openshift/cluster-storage-operator@63811bd3b9 (openshift/cluster-storage-operator#346).
=> OCPBUGS-13017: assets/hypershift/controller_sa: Set controller ServiceAccount imagePullSecrets

assets/controller.yaml
This PR fixes part of this bug: https://issues.redhat.com/browse/OCPBUGS-11882.
Basically adding this annotation to the pods which contains volumes or emptyDirs will allow the ClusterAutoscaler to drain the pods properly.
=> OCPBUGS-11882: Added safe-to-evict annotation to aws-ebs-csi-driver-controller pods

assets/controller.yaml
Last PR regarding this topic: https://github.com/openshift/aws-ebs-csi-driver-operator/pull/231
Initially in the deployment were not pretty clear, but once the HostedControlPlane is deployed, that volume shows as another emptyDir volume, so we need to add it to the annotation.
More details here: https://github.com/openshift/hypershift/pull/2647#issuecomment-1577532195
=> OCPBUGS-11882: Added safe-to-evict-local-volume annotation from bound-sa-token to ebs-controller

assets/controller.yaml
This is required by the new driver feature ["Interpolated tags in VolumeSnapshotClass"](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/tagging.md#snapshot-tagging).
cc @openshift/storage
=> STOR-1167: Enable extra-create-metadata to tag snapshots

assets/controller.yaml
Fixes https://issues.redhat.com/browse/OCPBUGS-15823
Note to reviewers - these changes are not there in upstream yet. But I did some measurements and IMO they make sense.  Generally speaking detaches are slower than attaches and in my measurements most attaches finished within 10-15s, detaches occasionally took slightly more, sometimes. 
So keeping a 60s interval of these operations IMO should be fine.
=> OCPBUGS-15823: Change CSI RPC call timeouts

.gitignore
`aws-ebs-csi-driver-operator` in `.gitignore` matches
`cmd/aws-ebs-csi-driver-operator`, which is in the repository and must not be ignored.
cc @openshift/storage 
This is necessary to get ART builds of csi-operator working - files required for build should not be ignored. See https://github.com/openshift/csi-operator/pull/65
=> STOR-1461: Remove existing path from .gitignore
